---
title: "prep"
author: "Alexandra Norris"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(wbstats)
library(countrycode)
library(tidyverse)
library(ggplot2)
library(essurvey)
library(sf)
library(gganimate)
library(plotly)
library(rnaturalearth)
library(plotly)
library(broom)
library(gt)

```


```{r}

# refugees by country or territory of asylum

ref <- wb(indicator = "SM.POP.REFG")

ref_2018 <- ref %>%
  filter(date == 2018) %>%
  select(iso3c, country, value)

```

```{r}
# refugees by country or territory of origin

ref_origin <- wb(indicator = "SM.POP.REFG.OR") %>%
  select(iso3c, country, value, date) %>%
  slice(1335:6493)

```


```{r, refugee country of asylum and gdp}

# data cleaning

gdp_percap_grow <- wb(indicator = "NY.GDP.PCAP.KD.ZG")

gdp_percap <- wb(indicator = "NY.GDP.PCAP.CD")

gdp <- wb(indicator = "NY.GDP.MKTP.CD")

gdp_grow_ref <- merge(gdp_percap_grow, ref, by = c("iso3c", "date", "country", "iso2c")) %>%
  mutate(gdp_percap_growth = value.x,
            refugee_number = value.y) %>%
  select(iso3c, iso2c, country, date, gdp_percap_growth, refugee_number)

with_gdp <- merge(gdp_grow_ref, gdp, by = c("iso3c", "date", "country", "iso2c")) %>%
  mutate(gdp = value) %>%
  select(iso3c, iso2c, country, date, gdp, gdp_percap_growth, refugee_number)

data <- merge(with_gdp, gdp_percap, by = c("iso3c", "date", "country", "iso2c")) %>%
  mutate(gdp_percap = value) %>%
  select(iso3c, iso2c, country, date, gdp, gdp_percap, gdp_percap_growth, refugee_number)

# refugees and gdp per cap growth 
  
  # regression

lm(gdp_percap_growth ~ refugee_number, data = data) %>%
  tidy(conf.int = TRUE, conf.level = 0.90) %>%
  mutate(name = c("Intercept", "Number of Refugees")) %>%
  select(name, estimate, conf.low, conf.high) %>%
  gt() %>%
  tab_header(title = "Refugee Counts and GDP Per Capita Growth") %>%
  cols_label(name = "", estimate = "Estimate", conf.low = "5th Percentile", conf.high = "95th Percentile")

  # graph

data %>%
  ggplot(aes(refugee_number, gdp_percap_growth)) +
  geom_point() +
  scale_x_continuous(labels = scales::comma) +
  geom_smooth(method = "lm") +
  labs(title = "Refugee Counts and GDP Per Capita Growth", x = "Number of Refugees", y = "GDP Percapita Growth Rate")

# refugees and gdp percap

lm(gdp_percap ~ refugee_number, data = data) %>%
  tidy(conf.int = TRUE, conf.level = 0.90) %>%
  mutate(name = c("Intercept", "Number of Refugees")) %>%
  select(name, estimate, conf.low, conf.high) %>%
  gt() %>%
  tab_header(title = "Refugee Counts and GDP Per Capita") %>%
  cols_label(name = "", estimate = "Estimate", conf.low = "5th Percentile", conf.high = "95th Percentile")

  # graph

data %>%
  ggplot(aes(gdp_percap, refugee_number)) +
  geom_point() +
  scale_x_continuous(labels = scales::comma) +
  geom_smooth(method = "lm")

# refugees and gdp

lm(gdp ~ refugee_number, data = data) %>%
  tidy(conf.int = TRUE, conf.level = 0.90) %>%
  mutate(name = c("Intercept", "Number of Refugees")) %>%
  select(name, estimate, conf.low, conf.high) %>%
  gt() %>%
  tab_header(title = "Refugee Counts and GDP") %>%
  cols_label(name = "", estimate = "Estimate", conf.low = "5th Percentile", conf.high = "95th Percentile")

  # graph

data %>%
  ggplot(aes(refugee_number, gdp)) + 
  geom_point() + 
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma) +
  geom_smooth(method = "lm", se = FALSE, color = "green")

```

```{r}
# refugee asylum location map 2018

plot_geo(data = ref_2018, locationmode = 'country names') %>%
  add_trace(
    z = ~value, locations = ~country, color = ~value, colors = "RdBu"
  )

```

```{r}

# rich countries and refugees
# according to the World Bank, "rich" countries are countries with GDP Per Cap >= $12,376
# https://datahelpdesk.worldbank.org/knowledgebase/articles/906519

data %>%
  filter(country == "North America") %>%
  ggplot(aes(gdp_percap, refugee_number)) +
  geom_point() +
  scale_x_continuous(labels = scales::comma) +
  geom_smooth(method = "lm") +
  labs(title = "Refugees")

# 
  
```


